version: "3.8"
services:
  database:
    image: ubuntu/mysql:edge
  backend:
    build: ./server
    volumes:
      - ./server:/app
    stdin_open: false
    tty: false
  client:
    build: ./client
    volumes:
      - ./client:/app
    stdin_open: true
    tty: true
    depends_on: 
      - backend